adject1 = input()
adject2 = input()
adject3 = input()
adject4 = input()
adject5 = input()
adject6 = input()

print(f"On a beautiful {adject1} day I went to the zoo. I saw a funny {adject2} monkey swinging from the trees. Then, I spotted")
print(f"a majestic {adject3} lion lounging in the sun. What a wild and {adject4} experience!")
print(f"After the trip to the zoo we went {adject5} for resting because we expected a big event coming next day")
print(f"My day was filled with {adject6} ")
